Repository babel/minify, pull requests merged in 2018-05, with the labels that each got.

#826 fix(merge-sibling-var): recalculate declarations when concatenating variables
  packages/babel-plugin-transform-merge-sibling-variables/src/index.js
  packages/babel-preset-minify/__tests__/minify-env-tests.js
Labels: Tag: Bug Fix

#827 chore: upgrade dependencies; add node 10; remove node 9
  .babelrc
  .travis.yml
  appveyor.yml
  babel.config.js
  package.json
  packages/babel-minify/package.json
  packages/babel-minify/src/index.js
  packages/babel-plugin-minify-dead-code-elimination/__tests__/dead-code-elimination-test.js
  packages/babel-plugin-minify-mangle-names/src/index.js
  packages/babel-plugin-minify-type-constructors/__tests__/type-constructors-test.js
  packages/babel-preset-minify/__tests__/minify-env-tests.js
  packages/gulp-babel-minify/__tests__/gulp-babili-test.js
  packages/gulp-babel-minify/package.json
  packages/gulp-babel-minify/src/index.js
  smoke/smoke-test.js
  utils/test-runner/src/index.js
  utils/test-transform/src/test-transform.js
  yarn.lock
Labels: Tag: Chore

#828 fix(const-folding): do not evaluate identifier in export specifiers
  packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/actual.js
  packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/babel.json
  packages/babel-plugin-minify-constant-folding/__tests__/fixtures/export-specifier/expected.js
  packages/babel-plugin-minify-constant-folding/src/index.js
Labels: Tag: Bug Fix

#833 add --save-dev to all packages' install instruction
  packages/babel-helper-evaluate-path/README.md
  packages/babel-helper-flip-expressions/README.md
  packages/babel-helper-is-void-0/README.md
  packages/babel-helper-mark-eval-scopes/README.md
  packages/babel-helper-remove-or-void/README.md
  packages/babel-helper-to-multiple-sequence-expressions/README.md
  packages/babel-plugin-minify-builtins/README.md
  packages/babel-plugin-minify-constant-folding/README.md
  packages/babel-plugin-minify-dead-code-elimination/README.md
  packages/babel-plugin-minify-flip-comparisons/README.md
  packages/babel-plugin-minify-guarded-expressions/README.md
  packages/babel-plugin-minify-infinity/README.md
  packages/babel-plugin-minify-mangle-names/README.md
  packages/babel-plugin-minify-numeric-literals/README.md
  packages/babel-plugin-minify-replace/README.md
  packages/babel-plugin-minify-simplify/README.md
  packages/babel-plugin-minify-type-constructors/README.md
  packages/babel-plugin-transform-inline-consecutive-adds/README.md
  packages/babel-plugin-transform-inline-environment-variables/README.md
  packages/babel-plugin-transform-member-expression-literals/README.md
  packages/babel-plugin-transform-merge-sibling-variables/README.md
  packages/babel-plugin-transform-minify-booleans/README.md
  packages/babel-plugin-transform-node-env-inline/README.md
  packages/babel-plugin-transform-property-literals/README.md
  packages/babel-plugin-transform-regexp-constructors/README.md
  packages/babel-plugin-transform-remove-console/README.md
  packages/babel-plugin-transform-remove-debugger/README.md
  packages/babel-plugin-transform-remove-undefined/README.md
  packages/babel-plugin-transform-simplify-comparison-operators/README.md
  packages/babel-plugin-transform-undefined-to-void/README.md
  packages/babel-preset-minify/README.md
Labels: Tag: Docs

#834 fix(deadcode): account for impure paths inside for statements
  packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/loops/actual.js
  packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/loops/expected.js
  packages/babel-plugin-minify-dead-code-elimination/src/index.js
  packages/babel-preset-minify/__tests__/minify-env-tests.js
Labels: Tag: Bug Fix

#831 fix: account for different scopes during path evaluation
  packages/babel-helper-evaluate-path/src/index.js
  packages/babel-plugin-minify-dead-code-elimination/__tests__/fixtures/issue-574/expected.js
  packages/babel-plugin-minify-dead-code-elimination/src/index.js
  packages/babel-plugin-minify-guarded-expressions/src/index.js
  packages/babel-plugin-minify-simplify/src/helpers.js
  packages/babel-plugin-minify-simplify/src/logical-expression.js
  packages/babel-preset-minify/__tests__/preset-tests.js
Labels: Tag: Bug Fix

#841 fix: minify infinity in expressions
  packages/babel-plugin-minify-infinity/__tests__/fixtures/bindings/actual.js
  packages/babel-plugin-minify-infinity/__tests__/fixtures/bindings/expected.js
  packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/actual.js
  packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/expected.js
  packages/babel-plugin-minify-infinity/src/index.js
Labels: Tag: Bug Fix

#572 Replace `x != undefined` with `x != null`
  packages/babel-plugin-minify-simplify/__tests__/fixtures/eqnull/actual.js
  packages/babel-plugin-minify-simplify/__tests__/fixtures/eqnull/expected.js
  packages/babel-plugin-minify-simplify/src/index.js
  packages/babel-plugin-transform-simplify-comparison-operators/src/index.js
Labels: Tag: New Feature

#846 fix: handle non array statements in evaluate helper
  packages/babel-helper-evaluate-path/src/index.js
  packages/babel-plugin-minify-constant-folding/__tests__/fixtures/issue-844/actual.js
  packages/babel-plugin-minify-constant-folding/__tests__/fixtures/issue-844/expected.js
Labels: Tag: Bug Fix

#852 refactor: update scripts to use transformSync and disable babel.config.js
  scripts/plugin-contribution.js
  scripts/plugin-timing.js
Labels: Tag: Internal

#853 refactor: split mangleScope logic to smaller functions
  packages/babel-plugin-minify-mangle-names/src/index.js
Labels: Tag: Internal

#856 perf(evaluate): convert paths to nodes as path.get is slow
  packages/babel-helper-evaluate-path/src/index.js
Labels: Tag: Perf

#857 perf(builtins): remove path.get calls
  packages/babel-plugin-minify-builtins/src/index.js
Labels: Tag: Perf

#858 refactor(simplify): hoist path.get calls
  packages/babel-plugin-minify-simplify/src/index.js
Labels: Tag: Internal

#863 Fix issue #862
  packages/gulp-babel-minify/src/index.js
Labels: Tag: Bug Fix
